### PR TITLE
Fixed redundant panel status notifications

### PR DESCRIPTION
**Pull request by balansse**
This update fixes the redundant panel notifications from Homekit when the panel is armed

### CODE REVIEW

**Comment by nstuyvesant** [comment]
I installed your branch globally. It showed several more sensors and the panel (vs. timcharper:master); however, after a few seconds or possibly triggers from motion sensors, it crashes:

```
[7/19/2019, 1:49:27 PM] [Vivint] received pubNub msg
[7/19/2019, 1:49:27 PM] [Vivint] {"_id":"<OMITTED>","da":{"d":[{"_id":26,"s":true}],"plctx":{"context_carrier":{"previous_handler":"Subscriber Update Handler","tracing_context":{"uber-trace-id":"<OMITTED>X:0:1"}},"mid":"<OMITTED>","ts":"2019-07-19T17:49:27.496"}},"op":"u","panid":<OMITTED>,"parid":1,"t":"account_partition"}
[7/19/2019, 1:49:27 PM] TypeError: Cannot read property 'getCharacteristic' of undefined
    at MotionSensor.notify (/usr/lib/node_modules/homebridge-vivint/lib/device_set.js:334:30)
    at MotionSensor.handlePatch (/usr/lib/node_modules/homebridge-vivint/lib/device_set.js:130:12)
    at msg.message.da.d.forEach (/usr/lib/node_modules/homebridge-vivint/lib/device_set.js:82:43)
    at Array.forEach (<anonymous>)
    at DeviceSet.handleMessage (/usr/lib/node_modules/homebridge-vivint/lib/device_set.js:80:28)
    at Object.message (/usr/lib/node_modules/homebridge-vivint/index.js:110:25)
    at /usr/lib/node_modules/homebridge-vivint/node_modules/pubnub/lib/core/components/listener_manager.js:65:40
    at Array.forEach (<anonymous>)
    at _class.announceMessage (/usr/lib/node_modules/homebridge-vivint/node_modules/pubnub/lib/core/components/listener_manager.js:64:23)
    at /usr/lib/node_modules/homebridge-vivint/node_modules/pubnub/lib/core/components/subscription_manager.js:599:35
```

**Comment by balansse** [comment]
I remember I also had something similar once - make sure to reset the cached accessories as it can sometimes trigger this. At some point I also updated node.js as well, don't know if it had any effect but I never experience any crashes anymore.

**Comment by nstuyvesant** [comment]
Thanks @balansse. That seemed to resolve the issue!

**Comment by jbullard120** [comment]
Great job! You should add the Overhead Garage Door sensor so it is assessable for other people in homekit. 

Device is "|| (data.ec == 2831)"

**device_set**
Line 221: `(data.t == "wireless_sensor") && ((data.ec == 1252) || (data.ec == 1251) || (data.ec == 655)) || (data.ec == 2831) //|| (data.ec == 2831) || (data.ec == 1269))`

**Pull request merged**
